### ISSUE TITLE
Enhancement: Un-hardcoding stuff for character modding

### ISSUE THREAD

**Issue by GeoDoesAnimations** [thepercentageguy/Unnamed-FNF-Engine#10]
So, I've been wondering. If you can, can you try to be able to Un-hardcode stuff like adding characters and offsets? that'd be fuckin cool, or really anything related to adding more characters

**Comment by thepercentageguy** [comment]
that's already planned actually!
I'll try to add this for 0.5

**Comment by thepercentageguy** [comment]
![code](https://user-images.githubusercontent.com/54141759/132555208-72b78fec-590a-4739-82aa-fc241644ac47.png)
happening!

**Comment by thepercentageguy** [comment]
just commited the change
