### ISSUE TITLE
Enhancement: Hitsound playing repeatedly on long notes

### ISSUE THREAD

**Issue by Goldenegg000** [thepercentageguy/Unnamed-FNF-Engine#17]
## What is your suggestion, and why should it be implemented?
when holding long notes it repeatedly plays the hit sound effect,
it would be better if the hit sound effect only plays only 1 time on the long note or on keypresses.

**Comment by thepercentageguy** [comment]
# This issue will be DISCARDED
Reason:

- [ ] This has been confirmed to not be a bug
- [x] Wrong label (label should be 'bug')
- [ ] has already been fixed
- [ ] other: __
