### ISSUE TITLE
Bug Report: Hitsound playing repeatedly on long notes

### ISSUE THREAD

**Issue by Goldenegg000** [thepercentageguy/Unnamed-FNF-Engine#18]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)
[weed]: <> (IF YOU DO NOT USE THIS TEMPLATE THERE IS A VERY BIG CHANCE YOUR ISSUE WILL SIMPLY BE DISCARDED!)
[weed]: <> (MAKE SURE TO TROUBLESHOOT YOUR ISSUE AND CONFIRM IT IS ACTUALLY A BUG!)
[weed]: <> (IF YOUR ISSUE SIMPLY GETS DISCARDED IT'S MOST LIKELY NOT A BUG!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### What platform do you play on?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] Gamejolt (online)
- [x] Windows
- [ ] Mac
- [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? and are you using a Pre-Release? Look in the bottom left corner of the main menu. (ex: 0.2.0 or 0.3.0, shit like that)
0.4

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
playing any song.

## Please describe your issue. Provide extensive detail and images if possible.
when holding long notes it repeatedly plays the hit sound effect.

**Comment by thepercentageguy** [comment]
fixed with 0.5
