### ISSUE TITLE
Enhancement: Updated charts from FNF v0.2.8

### ISSUE THREAD

**Issue by ScrubRTA** [thepercentageguy/Unnamed-FNF-Engine#22]
No current engine still uses the old charts from before the Week 7 update. Kade added the new charts to Kade Engine 3 months ago in version 1.5.
Not to mention, the old charts are desynced everywhere.

**Comment by thepercentageguy** [comment]
thanks for the reminder

**Comment by thepercentageguy** [comment]
done
