### ISSUE TITLE
Enhancement: Constant scroll speed value option

### ISSUE THREAD

**Issue by ScrubRTA** [thepercentageguy/Unnamed-FNF-Engine#23]
Having the scroll speed be too fast to read might not be considered fair depending on who you ask. I personally can't read anything over 2.0 scroll speed for the most part, and most Hard charts scroll faster than that.

**Comment by thepercentageguy** [comment]
gonna happen with 0.6

**Comment by thepercentageguy** [comment]
Implemented slightly differently, songs can't have a higher scrollspeed than 3 anymore.
