### ISSUE TITLE
Enhancement: Accuracy %

### ISSUE THREAD

**Issue by ScrubRTA** [thepercentageguy/Unnamed-FNF-Engine#26]
There are 3 major types of accuracy I've seen in FNF engines:
1. Binary accuracy: hit (100%) or miss (0%)
2. Standard accuracy, which covers numbers in between 100% and 0% depending on judgments.
3. Complex accuracy, which generally is supposed to time your hits down to the millisecond. While this makes 100% impossible, it allows players to push past MFC if they feel like the Sick judgement window is too lenient.

This often leads to the introduction of a grading system. Kade Engine uses Etterna's grading system (designed for Complex accuracy) which goes from "D" to "A", then "A.", "A:", "AA", ... up to "AAAAA" for 100% (or very close to 100%). Quaver and osu! use accuracy systems that fit more in "Standard" territory; Quaver is capped at "X" grade, and osu! is capped at "SS". Clone Hero doesn't have judgements other than hit or miss (so, Binary accuracy), but it still has a score-based grading system based on a number of "stars" between 1 and 7.

**Comment by thepercentageguy** [comment]
The kinda of % accuracy rating in UFNF rn is on the end screen showing you how many you hit, i might add option 2, or i might keep it the way it is rn and just add the % to the scoretext
