### ISSUE TITLE
[Bug]: Miss Animations playing when you didn't miss.

### ISSUE THREAD

**Issue by SpinnableBlue** [thepercentageguy/Unnamed-FNF-Engine#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

FunkinCloth#0420 < Discord

### What happened?

In this video: https://www.youtube.com/watch?v=iZ7Brmk3nrY&ab_channel=Thepercentageguy
You can see the Miss Animations play even when you hit a note without missing.

### Version

0.6 (unreleased Pre-release)

### Relevant log output

```shell
N/A
```

**Comment by thepercentageguy** [comment]
fixed with 0.7
