### ISSUE TITLE
Bug Report: Dropped Inputs

### ISSUE THREAD

**Issue by FunkinCloth** [thepercentageguy/Unnamed-FNF-Engine#3]
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
Latest ( 0.3? )

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
https://streamable.com/wj5t1a

## Please describe your issue. Provide extensive detail and images if possible.
notes missed even when pressed

**Comment by thepercentageguy** [comment]
# This issue will be DISCARDED
Reason:

- [x] This has been confirmed to not be a bug
- [ ] Wrong label
- [ ] has already been fixed
- [ ] other: __
