### ISSUE TITLE
Enhancement: "Panic" Animations

### ISSUE THREAD

**Issue by SpinnableBlue** [thepercentageguy/Unnamed-FNF-Engine#30]
## What is your suggestion, and why should it be implemented?
Panic Animations for the BF for when you're low on Health, Basically if you are on low health it will switch to using the Panic Animations sense BF is low on health and it makes sense for him to be Panicking.

Reason it should be added: Not really any reason, just an idea i had that you most likely wont add lmao.

**Comment by thepercentageguy** [comment]
if you get me panic animations i'll consider

**Comment by FunkinCloth** [comment]
bet
