### ISSUE TITLE
[Bug]: List of Issues for 0.6 

### ISSUE THREAD

**Issue by SpinnableBlue** [thepercentageguy/Unnamed-FNF-Engine#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Discord

### What happened?

- Middle Scroll with no Constant Scrollspeed is Broken
- Chart Editor resets some Settings
- Any song with a Space doesn't load
- Thorns doesn't have Dialogue?

### Version

0.6

### Relevant log output

```shell
N/A
```

**Comment by thepercentageguy** [comment]
fixed with 0.6.1 hopefully
