### ISSUE TITLE
Enhancement: Loading Screens

### ISSUE THREAD

**Issue by FunkinCloth** [thepercentageguy/Unnamed-FNF-Engine#5]
## What is your suggestion, and why should it be implemented?
Loading Screens for Loading Songs, Sense when you start a Song it has to load the Notes with the correct sprites now, Which takes awhile (at least on my device), Having a loading screen would probably be nice.

**Comment by thepercentageguy** [comment]
Loading screens are planned and will probably happen with **0.5**
